version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:476a1024936901889147f53d2a3d8e71e99d76404972d583825514f5608083dc
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:3.0-alpine@sha256:944eae3da4a1fa4beb9796e62a9bdcac627800eb56dbc6f668dfb9b15e58719f
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"